call: evaluate

evaluation:
  episode_length: 2000
  count: 32
  datasets:
    - mnist
    - fashion_mnist
    - random
    - emnist
    - kmnist
    - sum
    - cifar10

checkpoint:
  restore:
    # TODO insert wandb_path here
    run_path: 'entity/project/id'
